# Generated by Django 5.1.3 on 2025-03-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='token',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
